[package]
name = "skv"
publish = false
edition = "2021"
license = "MPL-2.0"

[dependencies]
chrono = "0.4"
futures = "0.3"
hashbrown = "0.14"
rusqlite = { version = "0.31.0", features = ["functions", "bundled"] }
serde = "1"
serde_json = { version = "1", features = ["float_roundtrip"] }
thiserror = "1"

[dev-dependencies]
tempfile = "3"
